"""fix document table

Revision ID: 2e9637530317
Revises: 376369171de3
Create Date: 2025-12-05 13:15:55.579846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e9637530317'
down_revision: Union[str, Sequence[str], None] = '376369171de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    document_status_enum = postgresql.ENUM(
        'REQUEST', 'PROCESSING', 'ACTIVE', 'FAIL',
        name='documentstatus',
        create_type=False
    )

    op.drop_constraint(
        'fk_documents_current_version_id',
        'documents',
        type_='foreignkey'
    )

    op.drop_constraint(
        'document_versions_document_id_fkey',
        'document_versions',
        type_='foreignkey'
    )

    op.drop_index('ix_document_versions_id', table_name='document_versions')
    op.drop_index('ix_documents_id', table_name='documents')

    op.drop_table('document_versions')
    op.drop_table('documents')

    op.create_table('documents_new',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('status', document_status_enum, nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_new_id'), 'documents_new', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_versions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('document_versions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('format', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('uploader_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='document_versions_document_id_fkey'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], name='document_versions_uploader_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='document_versions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_document_versions_id', 'document_versions', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('tags', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('current_version_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name='documents_creator_id_fkey'),
    sa.ForeignKeyConstraint(['current_version_id'], ['document_versions.id'], name='fk_documents_current_version_id'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='documents_department_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='documents_pkey')
    )
    op.create_index('ix_documents_id', 'documents', ['id'], unique=False)
    op.drop_index(op.f('ix_documents_new_id'), table_name='documents_new')
    op.drop_table('documents_new')
    # ### end Alembic commands ###
