"""add token_blacklist and user fields

Revision ID: 4046fafbc4a0
Revises: bd43cf121469
Create Date: 2025-11-28 13:45:30.993147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4046fafbc4a0'
down_revision: Union[str, Sequence[str], None] = 'bd43cf121469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
