"""change status

Revision ID: 71fc97c0b8ce
Revises: ae7c9136e04d
Create Date: 2025-12-03 09:06:53.560062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71fc97c0b8ce'
down_revision: Union[str, Sequence[str], None] = 'ae7c9136e04d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    documentstatus = sa.Enum('REQUEST', 'PROCESSING', 'ACTIVE', 'FAIL', name='documentstatus')
    documentstatus.create(op.get_bind(), checkfirst=True)

    op.create_table(
        'user_departments',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('department_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['department_id'], ['departments.id']),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('user_id', 'department_id')
    )

    op.alter_column(
        'chat_sessions', 'user_agent',
        existing_type=sa.VARCHAR(length=255),
        nullable=False
    )

    op.alter_column(
        'documents', 'status',
        existing_type=sa.VARCHAR(length=50),
        type_=documentstatus,
        existing_nullable=False,
        postgresql_using="status::documentstatus"
    )
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    documentstatus = sa.Enum('REQUEST', 'PROCESSING', 'ACTIVE', 'FAIL', name='documentstatus')

    op.alter_column(
        'documents', 'status',
        existing_type=documentstatus,
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
        postgresql_using="status::text"
    )

    op.alter_column(
        'chat_sessions', 'user_agent',
        existing_type=sa.VARCHAR(length=255),
        nullable=True
    )

    op.drop_table('user_departments')

    documentstatus.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
