"""update user model

Revision ID: 8bc81c17c465
Revises: f1027a5bd3dd
Create Date: 2025-11-25 15:04:18.591151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import bcrypt
from datetime import datetime
import os

# Delay reading admin credentials until runtime (inside upgrade)
# so alembic can import revision files (e.g. for `alembic heads`) without
# requiring environment variables to be present at import time.

# revision identifiers, used by Alembic.
revision: str = '8bc81c17c465'
down_revision: Union[str, Sequence[str], None] = 'f1027a5bd3dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    
    # Only create user_departments if it doesn't exist
    if 'user_departments' not in inspector.get_table_names():
        op.create_table('user_departments',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('department_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('user_id', 'department_id')
        )
    
    # Check if columns exist before modifying
    columns = [col['name'] for col in inspector.get_columns('users')]
    
    if 'campus' not in columns and 'campus_id' in columns:
        op.add_column('users', sa.Column('campus', sa.String(length=10), nullable=False))
        op.drop_column('users', 'campus_id')
    
    if 'notification_email' in columns:
        op.drop_column('users', 'notification_email')
    
    if 'is_active' in columns:
        op.drop_column('users', 'is_active')
    # ### end Alembic commands ###

    # Seed initial admin if not exists
    # Read credentials at runtime so we can still import/list migrations.
    ADMIN_DEFAULT_USERNAME = os.getenv('ADMIN_DEFAULT_USERNAME')
    ADMIN_DEFAULT_EMAIL = os.getenv('ADMIN_DEFAULT_EMAIL')
    ADMIN_DEFAULT_PASSWORD = os.getenv('ADMIN_DEFAULT_PASSWORD')

    if not ADMIN_DEFAULT_USERNAME or not ADMIN_DEFAULT_EMAIL or not ADMIN_DEFAULT_PASSWORD:
        raise ValueError(
            "ADMIN_DEFAULT_USERNAME, ADMIN_DEFAULT_EMAIL and ADMIN_DEFAULT_PASSWORD must be set before running this migration."
        )

    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)

    # Check if admin exists
    admin_count = session.query(sa.func.count('*')).select_from(sa.table('users')).where(sa.column('username') == ADMIN_DEFAULT_USERNAME).scalar()

    if admin_count == 0:
        hashed_pw = bcrypt.hashpw(ADMIN_DEFAULT_PASSWORD.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
        insert_stmt = sa.table('users',
            sa.column('username'), sa.column('email'), sa.column('campus'),
            sa.column('password_hash'), sa.column('role'),
            sa.column('failed_attempts'), sa.column('is_locked'), sa.column('created_at')
        ).insert().values(
            username=ADMIN_DEFAULT_USERNAME,
            email=ADMIN_DEFAULT_EMAIL,
            campus='MAIN',
            password_hash=hashed_pw,
            role='admin',
            failed_attempts=0,
            is_locked=False,
            created_at=datetime.utcnow()
        )
        session.execute(insert_stmt)
        session.commit()
        print("Initial admin created.")
    else:
        print("Admin already exists.")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('notification_email', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('campus_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_column('users', 'campus')
    op.drop_table('user_departments')
    # ### end Alembic commands ###
