"""add token_blacklist table

Revision ID: 9fd90da3b1c8
Revises: dac48aab7df1
Create Date: 2025-11-27 09:36:37.630400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fd90da3b1c8'
down_revision: Union[str, Sequence[str], None] = 'dac48aab7df1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_column('users', 'campus')
    op.drop_column('users', 'email')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'address')
    op.drop_column('users', 'image')
    op.drop_column('users', 'is_locked')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_locked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('campus', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_email_key', 'users', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
