"""drop table messages and queryLog

Revision ID: d7165892e3a5
Revises: 709c209cad81
Create Date: 2025-11-26 14:59:26.179192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7165892e3a5'
down_revision: Union[str, Sequence[str], None] = '709c209cad81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_messages_query_log_id_fkey', 'chat_messages', type_='foreignkey')
    op.drop_index(op.f('ix_chat_messages_query_log_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')

    op.drop_index(op.f('ix_query_logs_id'), table_name='query_logs')
    op.drop_table('query_logs')

    op.add_column(
        'chat_sessions',
        sa.Column('channel', sa.String(length=50), nullable=False, server_default='widget'),
    )
    op.alter_column('chat_sessions', 'channel', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'channel')
    op.create_table('chat_messages',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.Column('fallback', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('latency_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sources', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('feedback', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('feedback_comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('query_log_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['query_log_id'], ['query_logs.id'], name=op.f('chat_messages_query_log_id_fkey')),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name=op.f('chat_messages_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_messages_pkey'))
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_query_log_id'), 'chat_messages', ['query_log_id'], unique=False)
    op.create_table('query_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('lang', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('response_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('fallback', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('feedback', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('channel', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('query_logs_pkey'))
    )
    op.create_index(op.f('ix_query_logs_id'), 'query_logs', ['id'], unique=False)
    # ### end Alembic commands ###
