"""add department model

Revision ID: f1027a5bd3dd
Revises: dac48aab7df1
Create Date: 2025-11-24 09:20:54.166312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1027a5bd3dd'
down_revision: Union[str, Sequence[str], None] = 'dac48aab7df1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.add_column('document_versions', sa.Column('uploader_id', sa.Integer(), nullable=True))
    op.drop_constraint('document_versions_uploaded_by_fkey', 'document_versions', type_='foreignkey')
    op.create_foreign_key(None, 'document_versions', 'users', ['uploader_id'], ['id'])
    op.drop_column('document_versions', 'uploaded_by')
    op.add_column('documents', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.drop_constraint('documents_created_by_fkey', 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['creator_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'departments', ['department_id'], ['id'])
    op.drop_column('documents', 'created_by')
    op.add_column('users', sa.Column('notification_email', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('campus_id', sa.String(length=10), nullable=False))
    op.add_column('users', sa.Column('is_locked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_locked')
    op.drop_column('users', 'campus_id')
    op.drop_column('users', 'notification_email')
    op.add_column('documents', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key('documents_created_by_fkey', 'documents', 'users', ['created_by'], ['id'])
    op.drop_column('documents', 'creator_id')
    op.drop_column('documents', 'department_id')
    op.add_column('document_versions', sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'document_versions', type_='foreignkey')
    op.create_foreign_key('document_versions_uploaded_by_fkey', 'document_versions', 'users', ['uploaded_by'], ['id'])
    op.drop_column('document_versions', 'uploader_id')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
